"""new fields in user model

Revision ID: 661c12e18b3b
Revises: 870d686a485f
Create Date: 2018-03-19 20:32:49.243078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '661c12e18b3b'
down_revision = '870d686a485f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
